"""Migrations must apply cleanly to an empty database, and must not drift from the models.

The drift check is the load-bearing test here: convention 6 in docs/DEVELOPMENT.md says every schema
change ships with a migration, and this is what makes forgetting one a red build rather than a
broken upgrade on somebody else's install.
"""

from __future__ import annotations

import sqlite3
from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected

REPO_ROOT = Path(__file__).resolve().parents[1]

EXPECTED_TABLES = {
    "users",
    "radarr_instances",
    "sonarr_instances",
    "settings",
    "dismissed_items",
    "spinoff_mappings",
    "collection_excludes",
    "included_libraries",
    "activity_log",
}


def _alembic_config(db_path: Path) -> Config:
    config = Config(str(REPO_ROOT / "alembic.ini"))
    config.set_main_option("script_location", str(REPO_ROOT / "app" / "migrations"))
    config.set_main_option("sqlalchemy.url", f"sqlite:///{db_path}")
    config.attributes["configure_logger"] = False
    return config


def test_migration_applies_to_empty_database(db_path: Path) -> None:
    assert not db_path.exists()

    command.upgrade(_alembic_config(db_path), "head")

    with sqlite3.connect(db_path) as conn:
        tables = {row[0] for row in conn.execute("SELECT name FROM sqlite_master WHERE type='table'")}

    assert EXPECTED_TABLES <= tables
    assert "alembic_version" in tables


def test_models_match_migrations(db_path: Path) -> None:
    """`alembic check` fails if the models describe a schema the migrations don't produce."""
    config = _alembic_config(db_path)
    command.upgrade(config, "head")

    try:
        command.check(config)
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - only on a real drift
        pytest.fail(f"Models have drifted from the migrations; add a migration.\n{exc}")


def test_downgrade_returns_to_empty(db_path: Path) -> None:
    config = _alembic_config(db_path)
    command.upgrade(config, "head")
    command.downgrade(config, "base")

    with sqlite3.connect(db_path) as conn:
        tables = {row[0] for row in conn.execute("SELECT name FROM sqlite_master WHERE type='table'")}

    assert not (EXPECTED_TABLES & tables)


@pytest.mark.parametrize("had_servers", [True, False])
def test_0029_marks_existing_franchisarr_playlists_for_taking_in_only_on_an_install_with_servers(
    db_path: Path, had_servers: bool
) -> None:
    config = _alembic_config(db_path)
    command.upgrade(config, "0028")
    with sqlite3.connect(db_path) as conn:
        conn.execute("INSERT INTO settings (key, value, updated_at) VALUES ('playlist_sync_franchisarr', 'true', '2026-09-01')")
        if had_servers:
            conn.execute("INSERT INTO media_servers (name, kind, url, credential, enabled, created_at) "
                         "VALUES ('Plex', 'plex', 'http://plex:32400', 'x', 1, '2026-09-01')")

    command.upgrade(config, "0029")

    with sqlite3.connect(db_path) as conn:
        settings = dict(conn.execute("SELECT key, value FROM settings"))
    assert "playlist_sync_franchisarr" not in settings, "the switch is gone"
    assert (settings.get("franchisarr_playlists_to_adopt") == "true") is had_servers


def test_0034_drops_stored_fan_films_and_nothing_else(db_path: Path) -> None:
    config = _alembic_config(db_path)
    command.upgrade(config, "0033")
    with sqlite3.connect(db_path) as conn:
        conn.execute("INSERT INTO franchises (wikidata_id, name, kind, fetched_at) VALUES ('Q1', 'Wizarding World', "
                     "'media franchise', '2026-09-01')")
        for tmdb_id, title, kind in ((1, "Philosopher's Stone", "film"), (2, "Origins of the Heir", "fan film / film"),
                                     (3, "A Short", "short film"), (4, "Untagged", None)):
            conn.execute("INSERT INTO franchise_members (franchise_id, item_type, tmdb_id, title, kind) "
                         "VALUES ('Q1', 'movie', ?, ?, ?)", (tmdb_id, title, kind))

    command.upgrade(config, "0034")

    with sqlite3.connect(db_path) as conn:
        left = [row[0] for row in conn.execute("SELECT title FROM franchise_members ORDER BY tmdb_id")]
    assert left == ["Philosopher's Stone", "A Short", "Untagged"]
